Test cases for 0-add_integer module
===================================


Usage
=====

Importing function from the module:
    >>> add_integer = __import__('0-add_integer').add_integer

    >>> add_integer(1, 1)
    2

    >>> add_integer(6, -4)
    2

    >>> add_integer(-16, -4)
    -20

    >>> add_integer(2)
    100

    >>> add_integer(2.5, 5)
    7

    >>> add_integer(2.5)
    100

    >>> add_integer(10.5, -2)
    8

    >>> add_integer(-15.5, -2)
    -17


Error test cases:
    >>> add_integer(4, "hello")
    Traceback (most recent call last):
    TypeError: b must be an integer

    >>> add_integer(None)
    Traceback (most recent call last):
    TypeError: a must be an integer

    >>> add_integer('r', 1)
    Traceback (most recent call last):
    TypeError: a must be an integer

    >>> add_integer('u', 'n')
    Traceback (most recent call last):
    TypeError: a must be an integer

    >>> add_integer((1, 1))
    Traceback (most recent call last):
    TypeError: a must be an integer

    >>> add_integer(12, [])
    Traceback (most recent call last):
    TypeError: b must be an integer

    >>> add_integer("Hello")
    Traceback (most recent call last):
    TypeError: a must be an integer
